DROP DATABASE IF EXISTS VOLUNTEER_DB;

CREATE DATABASE VOLUNTEER_DB;

USE VOLUNTEER_DB;

CREATE TABLE VOLUNTEER(
    id INT NOT NULL AUTO_INCREMENT,
    VOL_Title VARCHAR(40) NOT NULL,
    VOL_Seats VARCHAR(40) NOT NULL,
    VOL_Address VARCHAR(40) NOT NULL,
    VOL_Date VARCHAR(40) NOT NULL,
    VOL_Time VARCHAR(40) NOT NULL,
    VOL_Duration VARCHAR(40) NOT NULL,
    VOL_Effort level VARCHAR(40) NOT NULL,

    PRIMARY KEY (id)
);

INSERT INTO VOLUNTEER(VOL_Title, VOL_Seats,VOL_Address, VOL_Date, VOL_Time, VOL_Duration, VOL_Effort level  ) VALUES (VOL,);