DROP DATABASE IF EXISTS VOLUNTEER_DB;

CREATE DATABASE VOLUNTEER_DB;

USE VOLUNTEER_DB;

CREATE TABLE VOLUNTEER(
    id INT NOT NULL AUTO_INCREMENT,
    VOL_Name VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO VOLUNTEER(Vol_Name,) VALUES (VOL);